'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { Field } from '@/components/Field';
import { Message } from '@/components/Message';
import { createClient } from '@/lib/supabase';
import type { Candidate } from '@/lib/types';
const supabase=createClient();
export default function Admin(){const [ok,setOk]=useState(false),[password,setPassword]=useState(''),[items,setItems]=useState<Candidate[]>([]),[err,setErr]=useState(''),[msg,setMsg]=useState(''); async function load(){const {data,error}=await supabase.from('candidates').select('*').eq('verification_status','pending').order('created_at',{ascending:true}); if(error)setErr(error.message); else setItems((data||[]) as Candidate[])} async function enter(e:FormEvent){e.preventDefault(); if(password !== process.env.NEXT_PUBLIC_ADMIN_DEMO_PASSWORD) return setErr('Invalid admin password.'); setOk(true); setErr(''); await load()} async function update(id:string,status:'verified'|'rejected'){const {error}=await supabase.from('candidates').update({verification_status:status}).eq('id',id); if(error)return setErr(error.message); setMsg(`Candidate ${status}.`); await load()} return <div className="space-y-6"><Link href="/" className="text-sm text-accent">← Home</Link><h1 className="text-3xl font-semibold">Admin verification</h1>{err&&<Message text={err} kind="error"/>}{msg&&<Message text={msg}/>} {!ok?<form onSubmit={enter} className="card max-w-md space-y-4"><Field label="Demo admin password"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></Field><button>Enter</button><p className="text-xs text-slate-500">Set NEXT_PUBLIC_ADMIN_DEMO_PASSWORD in your environment for this client-side demo gate.</p></form>:<section className="space-y-3"><h2 className="text-xl font-semibold">Pending candidates</h2>{items.length===0&&<Message text="No pending candidates." kind="info"/>}{items.map(c=><div className="card" key={c.id}><p className="font-medium">{c.full_name}</p><p className="text-sm text-slate-600">{c.course} · {c.college} · {c.location} · {c.phone}</p><div className="mt-3 flex gap-2"><button onClick={()=>update(c.id,'verified')}>Verify</button><button onClick={()=>update(c.id,'rejected')} className="bg-slate-700 hover:bg-slate-800">Reject</button></div></div>)}</section>}</div>}
