'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { Field } from '@/components/Field';
import { Message } from '@/components/Message';
import { createClient } from '@/lib/supabase';
import type { Application, Hospital, Job } from '@/lib/types';
const supabase=createClient();
export default function HospitalPage(){const [hospital,setHospital]=useState<Hospital|null>(null),[lookup,setLookup]=useState(''),[jobs,setJobs]=useState<Job[]>([]),[apps,setApps]=useState<Application[]>([]),[msg,setMsg]=useState(''),[err,setErr]=useState('');
async function load(hid=hospital?.id){if(!hid)return; const [{data:j},{data:a}]=await Promise.all([supabase.from('jobs').select('*').eq('hospital_id',hid).order('created_at',{ascending:false}),supabase.from('applications').select('*, candidates(*), jobs!inner(*)').eq('jobs.hospital_id',hid).order('created_at',{ascending:false})]); setJobs((j||[]) as Job[]); setApps((a||[]) as Application[])}
async function signup(e:FormEvent<HTMLFormElement>){e.preventDefault(); setErr(''); const fd=new FormData(e.currentTarget); const payload={hospital_name:String(fd.get('hospital_name')),contact_person:String(fd.get('contact_person')),phone:String(fd.get('phone')),email:String(fd.get('email')),location:String(fd.get('location'))}; const {data,error}=await supabase.from('hospitals').insert(payload).select().single(); if(error)return setErr(error.message); setHospital(data); setLookup(data.email); setMsg('Hospital registered. You can post jobs now.'); await load(data.id)}
async function find(e:FormEvent){e.preventDefault(); setErr(''); const {data,error}=await supabase.from('hospitals').select('*').or(`email.eq.${lookup},phone.eq.${lookup}`).maybeSingle(); if(error||!data)return setErr(error?.message||'No hospital found.'); setHospital(data); await load(data.id)}
async function post(e:FormEvent<HTMLFormElement>){e.preventDefault(); if(!hospital)return setErr('Open your hospital dashboard first.'); const fd=new FormData(e.currentTarget); const payload={hospital_id:hospital.id,role_title:String(fd.get('role_title')),required_qualification:String(fd.get('required_qualification')),experience_required:String(fd.get('experience_required')||''),location:String(fd.get('location')),vacancies:Number(fd.get('vacancies')||1),shift:String(fd.get('shift')||''),description:String(fd.get('description')||''),status:'open'}; const {error}=await supabase.from('jobs').insert(payload); if(error)return setErr(error.message); setMsg('Job posted.'); e.currentTarget.reset(); await load(hospital.id)}
async function updateApp(id:string,status:'shortlisted'|'rejected'){const {error}=await supabase.from('applications').update({status}).eq('id',id); if(error)return setErr(error.message); setMsg(`Applicant ${status}.`); await load();}
return <div className="space-y-8"><Link href="/" className="text-sm text-accent">← Home</Link><h1 className="text-3xl font-semibold">Hospital</h1>{msg&&<Message text={msg}/>} {err&&<Message text={err} kind="error"/>}<section className="grid gap-6 lg:grid-cols-2"><form onSubmit={signup} className="card space-y-4"><h2 className="text-xl font-semibold">Signup</h2>{['hospital_name','contact_person','phone','email','location'].map(n=><Field key={n} label={n.replaceAll('_',' ')}><input required name={n} type={n==='email'?'email':'text'}/></Field>)}<button>Register hospital</button></form><form onSubmit={find} className="card space-y-4"><h2 className="text-xl font-semibold">Dashboard lookup</h2><Field label="Email or phone"><input value={lookup} onChange={e=>setLookup(e.target.value)} required/></Field><button>Open dashboard</button>{hospital&&<p className="text-sm text-slate-600">Signed in as {hospital.hospital_name}</p>}</form></section>
<section className="grid gap-6 lg:grid-cols-2"><form onSubmit={post} className="card space-y-4"><h2 className="text-xl font-semibold">Post a job</h2>{['role_title','required_qualification','experience_required','location','shift'].map(n=><Field key={n} label={n.replaceAll('_',' ')}><input name={n} required={!['experience_required','shift'].includes(n)}/></Field>)}<Field label="vacancies"><input name="vacancies" type="number" min="1" defaultValue="1"/></Field><Field label="description"><textarea name="description" rows={4}/></Field><button disabled={!hospital}>Post job</button></form><div className="space-y-3"><h2 className="text-xl font-semibold">Posted jobs</h2>{jobs.map(j=><div className="card" key={j.id}><p className="font-medium">{j.role_title}</p><p className="text-sm text-slate-600">{j.location} · {j.status} · {j.vacancies} vacancies</p></div>)}</div></section>
<section className="space-y-3"><h2 className="text-2xl font-semibold">Applicants</h2>{apps.map(a=><div className="card" key={a.id}><p className="font-medium">{a.candidates?.full_name} for {a.jobs?.role_title}</p><p className="text-sm text-slate-600">{a.candidates?.course} · {a.candidates?.college} · {a.candidates?.experience_years ?? 0} yrs · {a.candidates?.phone} · {a.candidates?.verification_status}</p><p className="mt-1 text-sm">Application: {a.status}</p><div className="mt-3 flex gap-2"><button onClick={()=>updateApp(a.id,'shortlisted')}>Shortlist</button><button onClick={()=>updateApp(a.id,'rejected')} className="bg-slate-700 hover:bg-slate-800">Reject</button></div></div>)}</section></div>}
