'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase';
import type { Application, Candidate, Job } from '@/lib/types';
import { Field } from '@/components/Field';
import { Message } from '@/components/Message';

const supabase = createClient();
export default function CandidatePage() {
 const [msg,setMsg]=useState(''); const [err,setErr]=useState(''); const [candidate,setCandidate]=useState<Candidate|null>(null); const [lookup,setLookup]=useState(''); const [jobs,setJobs]=useState<Job[]>([]); const [apps,setApps]=useState<Application[]>([]); const [loc,setLoc]=useState(''); const [role,setRole]=useState('');
 async function signup(e:FormEvent<HTMLFormElement>){e.preventDefault(); setErr(''); const fd=new FormData(e.currentTarget); const payload={full_name:String(fd.get('full_name')),course:String(fd.get('course')),college:String(fd.get('college')),roll_number:String(fd.get('roll_number')),phone:String(fd.get('phone')),email:String(fd.get('email')),location:String(fd.get('location')),preferred_role:String(fd.get('preferred_role')),experience_years: fd.get('experience_years') ? Number(fd.get('experience_years')) : null, verification_status:'pending'}; const {data,error}=await supabase.from('candidates').insert(payload).select().single(); if(error) return setErr(error.message); setCandidate(data); setLookup(data.email); setMsg('Profile created. Verification is pending.'); await load(data.id);}
 async function findProfile(e:FormEvent){e.preventDefault(); setErr(''); const {data,error}=await supabase.from('candidates').select('*').or(`email.eq.${lookup},phone.eq.${lookup}`).maybeSingle(); if(error||!data) return setErr(error?.message||'No candidate found.'); setCandidate(data); await load(data.id);}
 async function load(cid=candidate?.id){let q=supabase.from('jobs').select('*, hospitals(hospital_name)').eq('status','open').order('created_at',{ascending:false}); if(loc) q=q.ilike('location',`%${loc}%`); if(role) q=q.ilike('role_title',`%${role}%`); const [{data:j},{data:a}]=await Promise.all([q, cid ? supabase.from('applications').select('*, jobs(*)').eq('candidate_id',cid).order('created_at',{ascending:false}) : Promise.resolve({data:[]})]); setJobs((j||[]) as Job[]); setApps((a||[]) as Application[]);}
 async function apply(jobId:string){if(!candidate) return setErr('Look up or create your profile first.'); setErr(''); const exists=apps.some(a=>a.job_id===jobId); if(exists) return setMsg('You already applied to this job.'); const {error}=await supabase.from('applications').insert({job_id:jobId,candidate_id:candidate.id,status:'applied'}); if(error) return setErr(error.message); setMsg('Application submitted.'); await load(candidate.id);}
 useEffect(()=>{load();},[]);
 return <div className="space-y-8"><Link href="/" className="text-sm text-accent">← Home</Link><h1 className="text-3xl font-semibold">Candidate</h1>{msg&&<Message text={msg}/>} {err&&<Message text={err} kind="error"/>}
 <section className="grid gap-6 lg:grid-cols-2"><form onSubmit={signup} className="card space-y-4"><h2 className="text-xl font-semibold">Signup</h2>{['full_name','course','college','roll_number','phone','email','location','preferred_role'].map(n=><Field key={n} label={n.replaceAll('_',' ')}><input required name={n} type={n==='email'?'email':'text'}/></Field>)}<Field label="experience years"><input name="experience_years" type="number" step="0.1" min="0"/></Field><button>Create profile</button></form>
 <div className="space-y-6"><form onSubmit={findProfile} className="card space-y-4"><h2 className="text-xl font-semibold">Dashboard lookup</h2><Field label="Email or phone"><input value={lookup} onChange={e=>setLookup(e.target.value)} required/></Field><button>Open dashboard</button></form>{candidate&&<div className="card"><h2 className="text-xl font-semibold">Profile</h2><p>{candidate.full_name} · {candidate.course}</p><p className="text-slate-600">{candidate.location} · {candidate.email}</p><p className="mt-2">Verification: <strong>{candidate.verification_status}</strong></p></div>}</div></section>
 <section className="space-y-4"><h2 className="text-2xl font-semibold">Open jobs</h2><div className="grid gap-3 sm:grid-cols-3"><input placeholder="Filter location" value={loc} onChange={e=>setLoc(e.target.value)}/><input placeholder="Filter role" value={role} onChange={e=>setRole(e.target.value)}/><button onClick={()=>load()}>Apply filters</button></div><div className="grid gap-3">{jobs.map(j=><article className="card" key={j.id}><h3 className="font-semibold">{j.role_title}</h3><p className="text-sm text-slate-600">{j.hospitals?.hospital_name} · {j.location} · {j.vacancies} vacancies</p><p className="mt-2 text-sm">{j.required_qualification}{j.experience_required?` · ${j.experience_required}`:''}</p><button className="mt-3" onClick={()=>apply(j.id)}>Apply</button></article>)}</div></section>
 <section className="space-y-3"><h2 className="text-2xl font-semibold">My applications</h2>{apps.map(a=><div className="card" key={a.id}><p className="font-medium">{a.jobs?.role_title}</p><p className="text-sm text-slate-600">{a.jobs?.location} · Status: {a.status}</p></div>)}</section></div>;
}
